name: beauty_salons_customer
description: Beauty Salons Customer Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # GET
  get: ^4.6.5
  get_storage: 2.0.3
  # DIO
  dio: 4.0.6
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 2.3.2
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: 3.2.1
  carousel_slider: 4.1.1
  flutter_svg: 1.0.3
  flutter_staggered_grid_view: 0.6.1
  image_picker: 0.8.5+3
  cupertino_icons: any
  shimmer: 2.0.0
  intl_phone_field: 3.1.0
  date_picker_timeline: 1.2.3
  flutter_local_notifications: 9.1.4
  intl:
  # WEB
  webview_flutter: 3.0.4
  flutter_html: 3.0.0-alpha.3
  url_launcher: 6.1.2
  # FIREBASE
  firebase_messaging: any
  cloud_firestore: any
  firebase_auth: any
  firebase_core: 2.15.0
  firebase_storage: any
  # GOOGLE MAPS
  google_maps_flutter: ^2.2.3
  google_places_flutter: ^2.0.5
  map_launcher: 2.2.2
  sms_autofill: ^2.2.0
  otp_autofill: ^2.1.0
  mobile_number: ^1.0.4
  location: ^4.4.0
  geocoder: ^0.2.1
  connectivity_plus: any
  dropdown_button2: ^2.0.0
  google_maps_place_picker_mb: ^3.0.1
  image_cropper: ^3.0.2
  file_picker: ^5.2.5
  permission_handler: ^10.2.0
#  google_maps_place_picker_mb:
#    git:
#      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
#      ref: 2.0.0-mb.18
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 2.2.0+1
dependency_overrides:
  file: ^6.1.4
  location: ^4.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
